### ISSUE TITLE
repetition...

### ISSUE THREAD

**Issue by lubegasimon** [microsoft/frontend-bootcamp#119]
i think ( TodoHeaderProps ) is some sort of repeatition because it was added to code line 16... https://github.com/Microsoft/frontend-bootcamp/blob/63e97d98a807fc0632306852c194fce8bc80f368/step2-06/demo/src/components/TodoHeader.tsx#L17

**Comment by ecraig12345** [comment]
Would you mind explaining what you mean in more detail?

**Comment by lubegasimon** [comment]
i mean since you have this, ```class TodoHeader extends React.Component<**TodoHeaderProp**s, TodoHeaderState> {```, then this is okay this way, ``` constructor(props: `~~TodoHeaderProps~~) {```

**Comment by lubegasimon** [comment]
i mean since you have this, class TodoHeader extends React.Component<**TodoHeaderProps**, TodoHeaderState> {, then this is okay this way, constructor(props: `<del>TodoHeaderProps </del>) {

**Comment by ecraig12345** [comment]
It's considered good practice (at least on the team that wrote this material) to specify the types of function parameters even if they could potentially be inferred. In our main codebase, we actually have a lint rule enforcing that function parameters have types. So I think the code should stay as-is.

**Comment by lubegasimon** [comment]
> It's considered good practice (at least on the team that wrote this material) to specify the types of function parameters even if they could potentially be inferred. In our main codebase, we actually have a lint rule enforcing that function parameters have types. So I think the code should stay as-is.

could you please tell me that ```lint rule```?

**Comment by ecraig12345** [comment]
Looked at this more and my last comment was slightly incorrect--we actually use a TypeScript compiler option `noImplicitAny` so that the compiler will give an error when the type of a parameter isn't specified. That's what would give an error if we removed the type here.

What I meant by "lint" is that our team uses a tool called [tslint](https://palantir.github.io/tslint/) to help enforce good coding practices in TypeScript code. If someone writes code that violates a lint rule, it will show an error when they build the code. There are similar lint tools for other languages.
