### ISSUE TITLE
Why only VS Code?

### ISSUE THREAD

**Issue by co16353sidak** [Microsoft/frontend-bootcamp#95]
Is there a possibility, that we could run this whole locally using some other editor than VS-Code.

I understand that it uses VS-Code's `code` terminal commands (or it's local editor), but there must be a way to access this using another editor, maybe Atom or WebStorm .etc
Or if we can be overly ambitious, make it editor independent. Is there a way this is possible or maybe it is but just need proper documentation?

**Comment by sudo-kaizen** [comment]
@co16353sidak Have you tried to run the code using other code editors and it was unsuccessful?

**Comment by fodra** [comment]
because Microsoft.

**Comment by co16353sidak** [comment]
@sudo-kaizen no I haven’t, i was wanting to try this though but I created an issue nevertheless to maybe get some information or dialogue going.

As i asked maybe there is a way to get this running using another code editor but the documentation lacks the information or steps.

**Comment by sudo-kaizen** [comment]
@co16353sidak The documentation doesn't say that you MUST use Visual Studio code. To run the program, what you NEED is npm, node and a terminal program. You can use other editors, but VS Code is preferred because of its integrated terminal. As long as you have run the code using `npm start` or `npm static`, it'll run and whatever changes you make in the editor will result in an update

**Comment by ecraig12345** [comment]
The goal of the bootcamp (both the online content and in-person trainings using this content) is to provide a clear, streamlined introduction to front-end web development. At almost every step, there are MANY alternative ways we could have done things, or alternative tech we could have used, but going into those alternatives upfront is more confusing than helpful for someone just getting started with this type of development.

We chose VS Code because it's widely used both inside and outside of Microsoft, has great built-in support for the rest of our tech stack, and provides an integrated terminal (again, streamlining the process for beginners). If anyone wants to fork the repo and make a version that goes through the steps with a different editor, you're welcome to do so!

**Comment by micahgodbolt** [comment]
Echoing what @ecraig12345 said, with our focus being on training Microsoft developers, we naturally reached for VS Code. We initially had instructions for setting up this tutorial with several different tools, but inevitably this caused confusion for some. You are certainly welcome to use whatever editor you like. Our setup instructions are only using VS Code to ensure that everyone can follow along and fewer people get lost. 

Going to close this issue down. If you want to give this training to other devs using another editor, feel free to fork/edit the README.md.
