### ISSUE TITLE
Better orientation on readme.

### ISSUE THREAD

**Issue by jonathanbcsouza** [Microsoft/frontend-bootcamp#97]
This is getting awesome!
But especially for students, some things are not clear.
Should we use the CodePen, VS Code, whatever?
What is exactly the flow?
 Should we read the demo first then go to the exercises, save and run HTML?
Should we use the demo as a reference?
Who is the presenter? Is this a part of some course?
Thanks.

**Comment by ecraig12345** [comment]
Great questions! This material was primarily meant for use with a two-day in-person internal training, with people following along with whatever the presenter is doing on-screen. We made it public in case others might find it useful (and to demonstrate to training attendees how the open source world works)...but definitely did NOT expect it to get attention on Reddit or end up trending on GitHub!

The flow for most of the steps is:
1. Demo: read the readme, possibly look at the code (the code is a more helpful reference in some steps than others)
2. Exercise: run `npm start` (unless otherwise noted), open the exercise page for that step, and follow the instructions.
  - For steps 1.1-1.3, coding is done in CodePen
  - Step 1.4 didn't have an exercise and was mostly watching live coding (needs to be fleshed out for people reading online). The `final` folder shows the end result.
  - For the other steps, the coding is in VS Code. If you have `npm start` running, it should automatically pick up your changes and refresh the browser on save to show results.

Hopefully that helps for now, but we definitely need to do some more work to clarify the material for online-only students.

**Comment by jonathanbcsouza** [comment]
@ecraig12345 Thanks for your explanation.
You are doing an awesome job
:)

**Comment by louis0808** [comment]
You'll get it
